# Generated by Django 3.0.5 on 2020-09-24 21:33

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('class_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeritAnalyser.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('teacher_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('teacher_password', models.CharField(max_length=300)),
                ('teacher_gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('passing_marks', models.IntegerField(default=0)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeritAnalyser.Class')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeritAnalyser.Subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeritAnalyser.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeritAnalyser.Teacher'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('student_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('student_password', models.CharField(max_length=300)),
                ('student_gender', models.CharField(max_length=6)),
                ('student_rollno', models.CharField(max_length=6)),
                ('tests_assigned', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=10989, size=999)),
                ('student_classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeritAnalyser.Class')),
            ],
        ),
    ]
