# Generated by Django 3.0.5 on 2020-10-03 20:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(db_index=True, max_length=4, unique=True)),
                ('class_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('teacher_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('teacher_password', models.CharField(max_length=500)),
                ('teacher_contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('user_type', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ids', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=99999, size=None)),
                ('student_marks', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=99999, size=None)),
                ('test_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('test_name', models.CharField(max_length=20)),
                ('passing_marks', models.IntegerField(default=0)),
                ('max_marks', models.IntegerField(default=0)),
                ('csv_filename', models.CharField(max_length=50)),
                ('highest_marks', models.IntegerField(default=0)),
                ('average_marks', models.IntegerField(default=0)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeritAnalyser.Class')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeritAnalyser.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('student_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('student_password', models.CharField(max_length=500)),
                ('student_rollno', models.CharField(max_length=6)),
                ('student_contact', models.CharField(max_length=10)),
                ('tests_assigned', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=99999, size=None)),
                ('student_classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeritAnalyser.Class')),
            ],
        ),
    ]
