# Generated by Django 3.0.6 on 2020-09-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeritAnalyser', '0002_questionpaper_results'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='results',
            new_name='result',
        ),
    ]
