# Generated by Django 3.0.6 on 2020-09-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeritAnalyser', '0003_auto_20200924_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
